///<reference path="../../../../modeloAbax.ts" /> 
///<reference path="../../../../modeloPlantillaAbax.ts" /> 
module abaxXBRL.templates {

    /**
     * Implementación de una clase con la definición de los elementos utilizados por la plantilla para presentar las definiciones del rol http://bmv.com.mx/role/ifrs/ccd/2015/ias_1_2014-03-05_role-800500
     * 
     * @author AbaxXBRL Template Generator
     * @version 1.0
     */
    export class http___bmv_com_mx_role_ifrs_ccd_2015_ias_1_2014_03_05_role_800500 implements abaxXBRL.model.DefinicionDeElementosPlantilla {

        /** La definición de los contextos utilizados por la plantilla */
        ContextosPlantillaPorId: { [idContextoPlantilla: string]: abaxXBRL.model.ContextoPlantilla };

        /** La definición de las unidades utilizadas por la plantilla */
        UnidadesPlantillaPorId: { [idUnidadPlantilla: string]: abaxXBRL.model.UnidadPlantilla };

        /** La definición de los hechos utilizados por la plantilla */
        HechosPlantillaPorId: { [idHechoPlantilla: string]: abaxXBRL.model.HechoPlantilla };

		/** El listado de fórmulas que se utilizan en un rol */
        ListadoDeFormulas: { [idFormula: string]: abaxXBRL.model.DefinicionFormula };

        /**
         * Constructor por defecto de la clase http___bmv_com_mx_role_ifrs_ccd_2015_ias_1_2014_03_05_role_800500
         */
        constructor() {

			this.ListadoDeFormulas = {};

            this.ContextosPlantillaPorId = {
  "trimestre_acumulado_actual": {
    "Id": "trimestre_acumulado_actual",
    "Periodo": {
      "Tipo": 2,
      "FechaInicio": "#fecha_2015_01_01",
      "FechaFin": "#fecha_2015_09_30",
      "FechaInstante": ""
    },
    "Entidad": {
      "Id": "#nombreEntidad",
      "EsquemaId": "#esquemaEntidad",
      "ContieneInformacionDimensional": false,
      "Segmento": null,
      "ValoresDimension": []
    },
    "ContieneInformacionDimensional": false,
    "Escenario": null,
    "ValoresDimension": []
  }
};

            this.UnidadesPlantillaPorId = {};
            
            this.HechosPlantillaPorId = {
  "A0ed989d6-388b-4590-bea0-877e4643aa73": {
    "Id": "A0ed989d6-388b-4590-bea0-877e4643aa73",
    "IdConcepto": "ifrs-full_DisclosureOfNotesAndOtherExplanatoryInformationExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A3583f010-f0b3-496e-ba46-cfcd67706c93": {
    "Id": "A3583f010-f0b3-496e-ba46-cfcd67706c93",
    "IdConcepto": "ifrs-full_DisclosureOfAccountingJudgementsAndEstimatesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A64276c91-fe3d-4340-b2ca-d2c19a92750a": {
    "Id": "A64276c91-fe3d-4340-b2ca-d2c19a92750a",
    "IdConcepto": "ifrs-full_DisclosureOfAccruedExpensesAndOtherLiabilitiesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A36c1dd62-3d46-4973-bd0c-ac80f973d040": {
    "Id": "A36c1dd62-3d46-4973-bd0c-ac80f973d040",
    "IdConcepto": "ifrs-full_DisclosureOfAllowanceForCreditLossesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A18533698-dde4-4751-b9c3-018aaecb738e": {
    "Id": "A18533698-dde4-4751-b9c3-018aaecb738e",
    "IdConcepto": "ifrs-full_DisclosureOfSignificantInvestmentsInAssociatesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A64c40f89-e59d-44f6-add9-61cd42766b48": {
    "Id": "A64c40f89-e59d-44f6-add9-61cd42766b48",
    "IdConcepto": "ifrs-full_DisclosureOfAuditorsRemunerationExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A42e5149f-9cb0-464f-aba0-7bf76b0d716c": {
    "Id": "A42e5149f-9cb0-464f-aba0-7bf76b0d716c",
    "IdConcepto": "ifrs-full_DisclosureOfAuthorisationOfFinancialStatementsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A515de101-e786-4956-a331-a93c7c9490e6": {
    "Id": "A515de101-e786-4956-a331-a93c7c9490e6",
    "IdConcepto": "ifrs-full_DisclosureOfAvailableforsaleAssetsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ae23573c8-03c1-420c-9621-ff0df545b1a0": {
    "Id": "Ae23573c8-03c1-420c-9621-ff0df545b1a0",
    "IdConcepto": "ifrs-full_DisclosureOfBasisOfConsolidationExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A1b8d21d7-db23-413c-aa10-8edcdcc5decd": {
    "Id": "A1b8d21d7-db23-413c-aa10-8edcdcc5decd",
    "IdConcepto": "ifrs-full_DisclosureOfBasisOfPreparationOfFinancialStatementsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Aca768335-eb27-429d-bd8a-cb75ac57778b": {
    "Id": "Aca768335-eb27-429d-bd8a-cb75ac57778b",
    "IdConcepto": "ifrs-full_DisclosureOfBorrowingsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A3e5eb13a-8fe3-490a-b919-816ba78e89c7": {
    "Id": "A3e5eb13a-8fe3-490a-b919-816ba78e89c7",
    "IdConcepto": "ifrs-full_DisclosureOfCashAndBankBalancesAtCentralBanksExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A9b39bfdb-0339-4b6b-8654-dfe4510911dd": {
    "Id": "A9b39bfdb-0339-4b6b-8654-dfe4510911dd",
    "IdConcepto": "ifrs-full_DisclosureOfCashAndCashEquivalentsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ad9c1d837-a706-4972-8c49-18f861842bb1": {
    "Id": "Ad9c1d837-a706-4972-8c49-18f861842bb1",
    "IdConcepto": "ifrs-full_DisclosureOfCashFlowStatementExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A3362b062-afea-4590-8e90-475ea5b41d2a": {
    "Id": "A3362b062-afea-4590-8e90-475ea5b41d2a",
    "IdConcepto": "ifrs-full_DisclosureOfChangesInAccountingPoliciesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A50831e5f-9abe-43a4-b048-2fcd12d41a87": {
    "Id": "A50831e5f-9abe-43a4-b048-2fcd12d41a87",
    "IdConcepto": "ifrs-full_DisclosureOfChangesInAccountingPoliciesAccountingEstimatesAndErrorsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A9f1de2da-c720-4338-9b37-8eaea7ca83a9": {
    "Id": "A9f1de2da-c720-4338-9b37-8eaea7ca83a9",
    "IdConcepto": "ifrs-full_DisclosureOfCollateralExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A736a5f76-1538-43d4-9f4f-4061813ffe6a": {
    "Id": "A736a5f76-1538-43d4-9f4f-4061813ffe6a",
    "IdConcepto": "ifrs-full_DisclosureOfClaimsAndBenefitsPaidExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Aae57edb7-6e9b-45dc-9f36-92389028bfb4": {
    "Id": "Aae57edb7-6e9b-45dc-9f36-92389028bfb4",
    "IdConcepto": "ifrs-full_DisclosureOfCommitmentsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ac8e8fd84-c991-4614-8f68-53997975f26e": {
    "Id": "Ac8e8fd84-c991-4614-8f68-53997975f26e",
    "IdConcepto": "ifrs-full_DisclosureOfCommitmentsAndContingentLiabilitiesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A705ace93-e5fc-429e-9a25-0f0c95a3a474": {
    "Id": "A705ace93-e5fc-429e-9a25-0f0c95a3a474",
    "IdConcepto": "ifrs-full_DisclosureOfContingentLiabilitiesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A9c84f2b5-61b7-4c95-a7ea-39b8105b77de": {
    "Id": "A9c84f2b5-61b7-4c95-a7ea-39b8105b77de",
    "IdConcepto": "ifrs-full_DisclosureOfCostOfSalesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A836bfe4d-b002-4ce9-aeb4-64f78af53af7": {
    "Id": "A836bfe4d-b002-4ce9-aeb4-64f78af53af7",
    "IdConcepto": "ifrs-full_DisclosureOfCreditRiskExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ac3724744-ccfc-42be-ba75-b8678db1ed73": {
    "Id": "Ac3724744-ccfc-42be-ba75-b8678db1ed73",
    "IdConcepto": "ifrs-full_DisclosureOfDebtSecuritiesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ad4302d78-a323-407a-aa26-ed3c972c0620": {
    "Id": "Ad4302d78-a323-407a-aa26-ed3c972c0620",
    "IdConcepto": "ifrs-full_DisclosureOfDeferredAcquisitionCostsArisingFromInsuranceContractsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A93386163-4529-43f1-bb19-7b068445a4e4": {
    "Id": "A93386163-4529-43f1-bb19-7b068445a4e4",
    "IdConcepto": "ifrs-full_DisclosureOfDeferredTaxesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A048cc30c-b51a-4878-a32d-1ef3b1e22bba": {
    "Id": "A048cc30c-b51a-4878-a32d-1ef3b1e22bba",
    "IdConcepto": "ifrs-full_DisclosureOfDepositsFromBanksExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Acc828ce8-2af9-4f3a-af80-e2dd38f243a1": {
    "Id": "Acc828ce8-2af9-4f3a-af80-e2dd38f243a1",
    "IdConcepto": "ifrs-full_DisclosureOfDepositsFromCustomersExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A65333ea9-c73c-423e-99f0-884017e6c52a": {
    "Id": "A65333ea9-c73c-423e-99f0-884017e6c52a",
    "IdConcepto": "ifrs-full_DisclosureOfDepreciationAndAmortisationExpenseExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ade51e0ce-8251-49dd-a743-a826e76dc32c": {
    "Id": "Ade51e0ce-8251-49dd-a743-a826e76dc32c",
    "IdConcepto": "ifrs-full_DisclosureOfDerivativeFinancialInstrumentsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ab3c24938-bcda-4367-ae72-d2085a452a06": {
    "Id": "Ab3c24938-bcda-4367-ae72-d2085a452a06",
    "IdConcepto": "ifrs-full_DisclosureOfDiscontinuedOperationsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A9591f601-43c3-4d47-b038-84e923c3aeb8": {
    "Id": "A9591f601-43c3-4d47-b038-84e923c3aeb8",
    "IdConcepto": "ifrs-full_DisclosureOfDividendsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A02d8814f-435e-4c3b-9ba3-010538b6366a": {
    "Id": "A02d8814f-435e-4c3b-9ba3-010538b6366a",
    "IdConcepto": "ifrs-full_DisclosureOfEarningsPerShareExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A1ba34102-6d8b-48bb-af0c-e0249283c4ac": {
    "Id": "A1ba34102-6d8b-48bb-af0c-e0249283c4ac",
    "IdConcepto": "ifrs-full_DisclosureOfEffectOfChangesInForeignExchangeRatesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Aa542b02e-e230-46ba-92d4-275662960306": {
    "Id": "Aa542b02e-e230-46ba-92d4-275662960306",
    "IdConcepto": "ifrs-full_DisclosureOfEventsAfterReportingPeriodExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A9142f12b-8a1c-401f-9faf-3c7599d63590": {
    "Id": "A9142f12b-8a1c-401f-9faf-3c7599d63590",
    "IdConcepto": "ifrs-full_DisclosureOfExpensesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ab3b63d1a-ed33-4504-8f67-1655c9346244": {
    "Id": "Ab3b63d1a-ed33-4504-8f67-1655c9346244",
    "IdConcepto": "ifrs-full_DisclosureOfExpensesByNatureExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A39994477-8028-4f4b-9be3-4d398425ac2b": {
    "Id": "A39994477-8028-4f4b-9be3-4d398425ac2b",
    "IdConcepto": "ifrs-full_DisclosureOfExplorationAndEvaluationAssetsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A9acea9e6-2332-49db-91f3-58e027a3d7d0": {
    "Id": "A9acea9e6-2332-49db-91f3-58e027a3d7d0",
    "IdConcepto": "ifrs-full_DisclosureOfFairValueMeasurementExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A2583f548-1d2b-428c-90c5-ed00fa691109": {
    "Id": "A2583f548-1d2b-428c-90c5-ed00fa691109",
    "IdConcepto": "ifrs-full_DisclosureOfFairValueOfFinancialInstrumentsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Abb303400-8513-40d8-9f2c-4cc9b2f354f9": {
    "Id": "Abb303400-8513-40d8-9f2c-4cc9b2f354f9",
    "IdConcepto": "ifrs-full_DisclosureOfFeeAndCommissionIncomeExpenseExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Adec2f32a-86cb-49d0-88a5-f6c0f7c85f01": {
    "Id": "Adec2f32a-86cb-49d0-88a5-f6c0f7c85f01",
    "IdConcepto": "ifrs-full_DisclosureOfFinanceCostExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A78d6670f-cf0f-476d-b0a9-4717a0db0cdc": {
    "Id": "A78d6670f-cf0f-476d-b0a9-4717a0db0cdc",
    "IdConcepto": "ifrs-full_DisclosureOfFinanceIncomeExpenseExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A986aa6b9-c859-4fa8-bf96-ef66b047c125": {
    "Id": "A986aa6b9-c859-4fa8-bf96-ef66b047c125",
    "IdConcepto": "ifrs-full_DisclosureOfFinanceIncomeExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A99dbe43c-578d-4100-b449-a9a4fa055db6": {
    "Id": "A99dbe43c-578d-4100-b449-a9a4fa055db6",
    "IdConcepto": "ifrs-full_DisclosureOfFinancialAssetsHeldForTradingExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ac4bde414-8002-45aa-862b-5d17840ae7fb": {
    "Id": "Ac4bde414-8002-45aa-862b-5d17840ae7fb",
    "IdConcepto": "ifrs-full_DisclosureOfFinancialInstrumentsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ad7492eda-55b5-4323-9bcd-e0463adc01b3": {
    "Id": "Ad7492eda-55b5-4323-9bcd-e0463adc01b3",
    "IdConcepto": "ifrs-full_DisclosureOfFinancialInstrumentsAtFairValueThroughProfitOrLossExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A10c070a3-f645-4112-af38-d5fbada11f1f": {
    "Id": "A10c070a3-f645-4112-af38-d5fbada11f1f",
    "IdConcepto": "ifrs-full_DisclosureOfFinancialInstrumentsDesignatedAtFairValueThroughProfitOrLossExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A3b079b96-13d1-45bc-85b5-2ebc3ec4ea17": {
    "Id": "A3b079b96-13d1-45bc-85b5-2ebc3ec4ea17",
    "IdConcepto": "ifrs-full_DisclosureOfFinancialInstrumentsHeldForTradingExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A7387fdba-b722-4211-878c-72f3f8582ad7": {
    "Id": "A7387fdba-b722-4211-878c-72f3f8582ad7",
    "IdConcepto": "ifrs-full_DisclosureOfFinancialLiabilitiesHeldForTradingExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A1a8e80c8-aeb1-40ed-9de1-eb7f074a1df3": {
    "Id": "A1a8e80c8-aeb1-40ed-9de1-eb7f074a1df3",
    "IdConcepto": "ifrs-full_DisclosureOfFinancialRiskManagementExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Af1c5eddd-c529-452a-9850-df40f7450eaa": {
    "Id": "Af1c5eddd-c529-452a-9850-df40f7450eaa",
    "IdConcepto": "ifrs-full_DisclosureOfFirstTimeAdoptionExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A09c74157-3254-4de1-b857-1110fd9e3b36": {
    "Id": "A09c74157-3254-4de1-b857-1110fd9e3b36",
    "IdConcepto": "ifrs-full_DisclosureOfGeneralAndAdministrativeExpenseExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A0299856c-40f3-44ab-9c58-7142794c303f": {
    "Id": "A0299856c-40f3-44ab-9c58-7142794c303f",
    "IdConcepto": "ifrs-full_DisclosureOfGeneralInformationAboutFinancialStatementsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ad2913d44-3a20-4f24-9085-92581d425f3e": {
    "Id": "Ad2913d44-3a20-4f24-9085-92581d425f3e",
    "IdConcepto": "ifrs-full_DisclosureOfGoingConcernExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A10062d70-fba6-436f-9550-b63b8fe318b4": {
    "Id": "A10062d70-fba6-436f-9550-b63b8fe318b4",
    "IdConcepto": "ifrs-full_DisclosureOfGoodwillExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A5f87c00d-9c76-4d3d-b9b5-b877c8b3959a": {
    "Id": "A5f87c00d-9c76-4d3d-b9b5-b877c8b3959a",
    "IdConcepto": "ifrs-full_DisclosureOfImpairmentOfAssetsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ad7e642a9-fd01-4060-b750-de7077ba8a83": {
    "Id": "Ad7e642a9-fd01-4060-b750-de7077ba8a83",
    "IdConcepto": "ifrs-full_DisclosureOfIncomeTaxExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A1ec0d99a-102e-4061-b381-e9bb41414a7c": {
    "Id": "A1ec0d99a-102e-4061-b381-e9bb41414a7c",
    "IdConcepto": "ifrs-full_DisclosureOfInsuranceContractsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A3755b88f-c2cf-4f7e-9a81-c72273e3fc4e": {
    "Id": "A3755b88f-c2cf-4f7e-9a81-c72273e3fc4e",
    "IdConcepto": "ifrs-full_DisclosureOfInsurancePremiumRevenueExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A5a71db51-ecc8-402e-93c8-dd9d7dd94d1d": {
    "Id": "A5a71db51-ecc8-402e-93c8-dd9d7dd94d1d",
    "IdConcepto": "ifrs-full_DisclosureOfIntangibleAssetsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Af8225650-525f-4d98-9002-a134bc4fee80": {
    "Id": "Af8225650-525f-4d98-9002-a134bc4fee80",
    "IdConcepto": "ifrs-full_DisclosureOfIntangibleAssetsAndGoodwillExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ac6a95c52-5ab5-4065-8af7-185324237452": {
    "Id": "Ac6a95c52-5ab5-4065-8af7-185324237452",
    "IdConcepto": "ifrs-full_DisclosureOfInterestExpenseExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ab1fcd5ed-e73a-4fa2-909d-87d54a9e256d": {
    "Id": "Ab1fcd5ed-e73a-4fa2-909d-87d54a9e256d",
    "IdConcepto": "ifrs-full_DisclosureOfInterestIncomeExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A2b6d25d9-aabb-4a07-8968-4dce146260c3": {
    "Id": "A2b6d25d9-aabb-4a07-8968-4dce146260c3",
    "IdConcepto": "ifrs-full_DisclosureOfInterestIncomeExpenseExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A778858d9-14ee-4309-be6f-45adf7bdf22b": {
    "Id": "A778858d9-14ee-4309-be6f-45adf7bdf22b",
    "IdConcepto": "ifrs-full_DisclosureOfInventoriesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A3f3b7842-6f1f-44d9-b59d-70a308e34a72": {
    "Id": "A3f3b7842-6f1f-44d9-b59d-70a308e34a72",
    "IdConcepto": "ifrs-full_DisclosureOfInvestmentContractsLiabilitiesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A705c45cb-5702-4e84-9f77-7b751081d3ef": {
    "Id": "A705c45cb-5702-4e84-9f77-7b751081d3ef",
    "IdConcepto": "ifrs-full_DisclosureOfInvestmentPropertyExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A16f618f9-ef31-46e8-8171-bf17a40f976b": {
    "Id": "A16f618f9-ef31-46e8-8171-bf17a40f976b",
    "IdConcepto": "ifrs-full_DisclosureOfInvestmentsAccountedForUsingEquityMethodExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A05bb4f6b-ad0a-45e0-b093-88a4d4b67114": {
    "Id": "A05bb4f6b-ad0a-45e0-b093-88a4d4b67114",
    "IdConcepto": "ifrs-full_DisclosureOfInvestmentsOtherThanInvestmentsAccountedForUsingEquityMethodExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A89d5b90e-5966-49f0-9708-2fd241930afe": {
    "Id": "A89d5b90e-5966-49f0-9708-2fd241930afe",
    "IdConcepto": "ifrs-full_DisclosureOfIssuedCapitalExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A1aa63314-9046-4b14-bc03-0f0295ab2f1c": {
    "Id": "A1aa63314-9046-4b14-bc03-0f0295ab2f1c",
    "IdConcepto": "ifrs-full_DisclosureOfJointVenturesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Acecaa28c-0574-4c93-b1df-2c56a51098d5": {
    "Id": "Acecaa28c-0574-4c93-b1df-2c56a51098d5",
    "IdConcepto": "ifrs-full_DisclosureOfLeasePrepaymentsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A5989eb73-b00e-4c87-97dd-83c1bcca06d1": {
    "Id": "A5989eb73-b00e-4c87-97dd-83c1bcca06d1",
    "IdConcepto": "ifrs-full_DisclosureOfLeasesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A4e0350a7-b623-4b2b-a4a7-38d38c468387": {
    "Id": "A4e0350a7-b623-4b2b-a4a7-38d38c468387",
    "IdConcepto": "ifrs-full_DisclosureOfLiquidityRiskExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Adc66c0c5-821d-4845-b124-be2f2360e3f9": {
    "Id": "Adc66c0c5-821d-4845-b124-be2f2360e3f9",
    "IdConcepto": "ifrs-full_DisclosureOfLoansAndAdvancesToBanksExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A9a07b809-155d-4369-86c3-8272c97255f1": {
    "Id": "A9a07b809-155d-4369-86c3-8272c97255f1",
    "IdConcepto": "ifrs-full_DisclosureOfLoansAndAdvancesToCustomersExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Aa2aa6e5c-63d0-4ef0-ab1e-fa72c952ccf8": {
    "Id": "Aa2aa6e5c-63d0-4ef0-ab1e-fa72c952ccf8",
    "IdConcepto": "ifrs-full_DisclosureOfMarketRiskExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A55d6eace-e354-4c19-aa4e-cefe30f7c404": {
    "Id": "A55d6eace-e354-4c19-aa4e-cefe30f7c404",
    "IdConcepto": "ifrs-full_DisclosureOfNetAssetValueAttributableToUnitholdersExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A338279c2-035f-4138-973d-fd2995a77950": {
    "Id": "A338279c2-035f-4138-973d-fd2995a77950",
    "IdConcepto": "ifrs-full_DisclosureOfNoncontrollingInterestsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ac112236b-55de-4472-945b-adb06419749b": {
    "Id": "Ac112236b-55de-4472-945b-adb06419749b",
    "IdConcepto": "ifrs-full_DisclosureOfNoncurrentAssetsHeldForSaleAndDiscontinuedOperationsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A0bd4528c-564e-4e68-af8a-b38652aec23d": {
    "Id": "A0bd4528c-564e-4e68-af8a-b38652aec23d",
    "IdConcepto": "ifrs-full_DisclosureOfNoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSaleExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Af31d4510-9e1c-43c8-8b8c-e7d1c3b8dd4c": {
    "Id": "Af31d4510-9e1c-43c8-8b8c-e7d1c3b8dd4c",
    "IdConcepto": "ifrs-full_DisclosureOfObjectivesPoliciesAndProcessesForManagingCapitalExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A373074fc-7bb3-48ab-af45-bcf3803828a1": {
    "Id": "A373074fc-7bb3-48ab-af45-bcf3803828a1",
    "IdConcepto": "ifrs-full_DisclosureOfOtherAssetsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ad2da8ba8-9251-4094-97c9-7cf89d77d1ec": {
    "Id": "Ad2da8ba8-9251-4094-97c9-7cf89d77d1ec",
    "IdConcepto": "ifrs-full_DisclosureOfOtherCurrentAssetsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A6b5e0bdd-6cd7-4c69-85c2-fbb2bb5103e3": {
    "Id": "A6b5e0bdd-6cd7-4c69-85c2-fbb2bb5103e3",
    "IdConcepto": "ifrs-full_DisclosureOfOtherCurrentLiabilitiesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A77aeb0e2-c0e1-4016-9785-8bfbc0d9b3ca": {
    "Id": "A77aeb0e2-c0e1-4016-9785-8bfbc0d9b3ca",
    "IdConcepto": "ifrs-full_DisclosureOfOtherLiabilitiesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A2f9b0602-a373-443c-a4fa-55cfeceac875": {
    "Id": "A2f9b0602-a373-443c-a4fa-55cfeceac875",
    "IdConcepto": "ifrs-full_DisclosureOfOtherNoncurrentAssetsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ac34b6238-4282-4ff0-a45c-d56669249f14": {
    "Id": "Ac34b6238-4282-4ff0-a45c-d56669249f14",
    "IdConcepto": "ifrs-full_DisclosureOfOtherNoncurrentLiabilitiesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Afc8c74af-6fc3-426c-a34e-e44f03eb9771": {
    "Id": "Afc8c74af-6fc3-426c-a34e-e44f03eb9771",
    "IdConcepto": "ifrs-full_DisclosureOfOtherOperatingExpenseExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A9bacb76b-f693-44e8-9393-918c148f45f0": {
    "Id": "A9bacb76b-f693-44e8-9393-918c148f45f0",
    "IdConcepto": "ifrs-full_DisclosureOfOtherOperatingIncomeExpenseExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A9c2a14f1-fd72-4bf4-857f-b60a3ba2a4f3": {
    "Id": "A9c2a14f1-fd72-4bf4-857f-b60a3ba2a4f3",
    "IdConcepto": "ifrs-full_DisclosureOfOtherOperatingIncomeExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Acd51ef5f-f657-47cb-aaca-eff66ecd5e0d": {
    "Id": "Acd51ef5f-f657-47cb-aaca-eff66ecd5e0d",
    "IdConcepto": "ifrs-full_DisclosureOfPrepaymentsAndOtherAssetsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A392d70d1-be1a-498c-bb05-c860e36254d2": {
    "Id": "A392d70d1-be1a-498c-bb05-c860e36254d2",
    "IdConcepto": "ifrs-full_DisclosureOfProfitLossFromOperatingActivitiesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A343da11a-85aa-43ee-ac19-c16cbc4a29dd": {
    "Id": "A343da11a-85aa-43ee-ac19-c16cbc4a29dd",
    "IdConcepto": "ifrs-full_DisclosureOfPropertyPlantAndEquipmentExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A4e9762e8-b51e-4eb7-88e5-8fa701551119": {
    "Id": "A4e9762e8-b51e-4eb7-88e5-8fa701551119",
    "IdConcepto": "ifrs-full_DisclosureOfProvisionsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A1169e931-80e8-4181-b973-fadb42f51459": {
    "Id": "A1169e931-80e8-4181-b973-fadb42f51459",
    "IdConcepto": "ifrs-full_DisclosureOfReclassificationOfFinancialInstrumentsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ad5bac7f1-41a8-45e7-b344-d8330ee822dc": {
    "Id": "Ad5bac7f1-41a8-45e7-b344-d8330ee822dc",
    "IdConcepto": "ifrs-full_DisclosureOfRecognisedRevenueFromConstructionContractsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A03edab1c-5c08-4c5d-9295-6eefb9d15143": {
    "Id": "A03edab1c-5c08-4c5d-9295-6eefb9d15143",
    "IdConcepto": "ifrs-full_DisclosureOfReinsuranceExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Aad25eb39-65a1-4223-9a4c-8d0c512307cb": {
    "Id": "Aad25eb39-65a1-4223-9a4c-8d0c512307cb",
    "IdConcepto": "ifrs-full_DisclosureOfRelatedPartyExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ac624f9f5-5468-403c-8b2f-272894b94ed2": {
    "Id": "Ac624f9f5-5468-403c-8b2f-272894b94ed2",
    "IdConcepto": "ifrs-full_DisclosureOfResearchAndDevelopmentExpenseExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A058fa457-53df-41ce-bdfb-e603e150174f": {
    "Id": "A058fa457-53df-41ce-bdfb-e603e150174f",
    "IdConcepto": "ifrs-full_DisclosureOfReservesAndOtherEquityInterestExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A8f58b46b-5cfe-4b0e-9c7a-f9cf63acac21": {
    "Id": "A8f58b46b-5cfe-4b0e-9c7a-f9cf63acac21",
    "IdConcepto": "ifrs-full_DisclosureOfRestrictedCashAndCashEquivalentsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Aadc23b4a-f6f1-4059-9b86-5e46ab3e51de": {
    "Id": "Aadc23b4a-f6f1-4059-9b86-5e46ab3e51de",
    "IdConcepto": "ifrs-full_DisclosureOfRevenueExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Abf111377-8ee9-41be-9f79-0cc6bd612204": {
    "Id": "Abf111377-8ee9-41be-9f79-0cc6bd612204",
    "IdConcepto": "ifrs-full_DisclosureOfServiceConcessionArrangementsExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A23e509eb-eee7-4aa8-b600-092bdc410dfe": {
    "Id": "A23e509eb-eee7-4aa8-b600-092bdc410dfe",
    "IdConcepto": "ifrs-full_DisclosureOfShareCapitalReservesAndOtherEquityInterestExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A76b8629a-edf3-484e-8784-96fdcafb5306": {
    "Id": "A76b8629a-edf3-484e-8784-96fdcafb5306",
    "IdConcepto": "ifrs-full_DisclosureOfSubordinatedLiabilitiesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A26ac5fe4-e475-4190-92de-2cff1b35dc13": {
    "Id": "A26ac5fe4-e475-4190-92de-2cff1b35dc13",
    "IdConcepto": "ifrs-full_DisclosureOfSignificantInvestmentsInSubsidiariesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ab7199429-dc78-4d78-aec8-a7463128a554": {
    "Id": "Ab7199429-dc78-4d78-aec8-a7463128a554",
    "IdConcepto": "ifrs-full_DisclosureOfSummaryOfSignificantAccountingPoliciesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A4ee746d3-f476-45a3-8d36-a77de9546512": {
    "Id": "A4ee746d3-f476-45a3-8d36-a77de9546512",
    "IdConcepto": "ifrs-full_DisclosureOfTaxReceivablesAndPayablesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A19a46d7c-7170-477d-92ab-5be664a66f29": {
    "Id": "A19a46d7c-7170-477d-92ab-5be664a66f29",
    "IdConcepto": "ifrs-full_DisclosureOfTradeAndOtherPayablesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ac4f38930-eb51-4c7c-a19b-165cc876bcf9": {
    "Id": "Ac4f38930-eb51-4c7c-a19b-165cc876bcf9",
    "IdConcepto": "ifrs-full_DisclosureOfTradeAndOtherReceivablesExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ae0b098f3-d3b4-4201-98a6-13c7b415321f": {
    "Id": "Ae0b098f3-d3b4-4201-98a6-13c7b415321f",
    "IdConcepto": "ifrs-full_DisclosureOfTradingIncomeExpenseExplanatory",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A2efb52e6-e37d-4fc0-bc2b-7f3a9253a71d": {
    "Id": "A2efb52e6-e37d-4fc0-bc2b-7f3a9253a71d",
    "IdConcepto": "mx_ccd_RisksRelatedToFinancialInstruments",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "Ae8670ca2-08b0-4c3b-abdc-65805284e522": {
    "Id": "Ae8670ca2-08b0-4c3b-abdc-65805284e522",
    "IdConcepto": "mx_ccd_InvestmentsKeptToMaturity",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A3daef244-e4ea-4899-b797-78d5c2afc3be": {
    "Id": "A3daef244-e4ea-4899-b797-78d5c2afc3be",
    "IdConcepto": "mx_ccd_ValueAddedTaxPositiveOnFavour",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A3442b6c2-00b8-4e38-9237-787ddbf83fb2": {
    "Id": "A3442b6c2-00b8-4e38-9237-787ddbf83fb2",
    "IdConcepto": "mx_ccd_NetAssets",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A531e6816-1bd3-4d27-b93d-4d961c27767a": {
    "Id": "A531e6816-1bd3-4d27-b93d-4d961c27767a",
    "IdConcepto": "mx_ccd_ForeingCurrencyPosition",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  },
  "A3036e6f2-27c1-40bc-9d4b-be8b01952168": {
    "Id": "A3036e6f2-27c1-40bc-9d4b-be8b01952168",
    "IdConcepto": "mx_ccd_InvestmentsInShares",
    "IdContextoPlantilla": "trimestre_acumulado_actual",
    "Hechos": [],
    "IdUnidadPlantilla": null,
    "ValorNumerador": null,
    "ValorDenominador": null,
    "Precision": null,
    "Decimales": null,
    "Valor": "#valorDefaultNoNumerico"
  }
};
        }
    }

}